n computer programming, boilerplate code or boilerplate refers to sections of code 
that have to be included in many places with little or no alteration.

To reduce the amount of boilerplate, many frameworks have been developed, e.g. Lombok for Java.[4] The same code as above is auto-generated by Lombok using Java annotations, which is a form of metaprogramming: 

@AllArgsConstructor
@Getter
@Setter
public class Pet {
    private String name;
    private Person owner;
}
