n computer programming, boilerplate code or boilerplate refers to sections of code 
that have to be included in many places with little or no alteration.

To reduce the amount of boilerplate, many frameworks have been developed, e.g. Lombok for Java.[4] The same code as above is auto-generated by Lombok using Java annotations, which is a form of metaprogramming: 

@AllArgsConstructor
@Getter
@Setter
public class Pet {
    private String name;
    private Person owner;
}



======================boilerPlate code for above code =================
    public class Pet {
    private String name;
    private Person owner;

    public Pet(String name, Person owner) {
        this.name = name;
        this.owner = owner;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Person getOwner() {
        return owner;
    }

    public void setOwner(Person owner) {
        this.owner = owner;
    }
}
